export const flashcards = [
    { front: "3 key processes in memory", back: "Encoding (forming a memory code), Storage (maintaining encoded information over time), Retrieval (recovering information from memory stores)" },
    { front: "Attention", back: "Focusing awareness on a narrowed range of stimuli or events" },
    { front: "Levels of processing", back: "Shallow processing: emphasizes the physical structure of the stimulus; Intermediate processing: emphasizes what a word sounds like; Deep processing: emphasizes the meaning of verbal input" },
    { front: "Level of processing theory", back: "Deeper levels of processing result in longer-lasting memory codes" },
    { front: "Elaboration", back: "Linking a stimulus to other information involved at the time of encoding" },
    { front: "Dual-coding theory", back: "Memory is enhanced by forming semantic and visual codes, since either can lead to recall" },
    { front: "Self-referent encoding", back: "Deciding how or whether information is personally relevant" },
    { front: "Sensory memory", back: "Preserves information in its original sensory form for a brief time" },
    { front: "Short-term memory", back: "Limited capacity store that maintains unrehearsed information for up to 20 seconds" },
    { front: "Rehearsal", back: "The process of repetitively verbalizing or thinking about information" },
    { front: "Chunk", back: "A group of familiar stimuli stored as a single unit" },
    { front: "Working memory", back: "Limited capacity storage system that temporarily maintains and stores information by providing an interface between perception, memory, and action" },
    { front: "Working memory capacity", back: "The ability to hold and manipulate information in conscious attention" },
    { front: "Long-term memory", back: "Unlimited capacity store that can hold information over lengthy periods of time" },
    { front: "Flashbulb memories", back: "Unusually vivid and detailed recollections of momentous events" },
    { front: "Clustering", back: "The tendency to remember similar or related items in groups" },
    { front: "Conceptual hierarchy", back: "A multilevel classification system based on common properties among items" },
    { front: "Schema", back: "An organized cluster of knowledge about a particular object or event abstracted from previous experience" },
    { front: "Semantic network", back: "Nodes representing concepts joined together by pathways that link related concepts" },
    { front: "Tip-of-the-tongue phenomenon", back: "Temporary inability to remember something you know, accompanied by a feeling that it's just out of reach" },
    { front: "Misinformation effect", back: "Participants' recall of an event they witnessed is altered by introducing misleading post-event information" },
    { front: "Source monitoring", back: "The process of making inferences about the origins of memories" },
    { front: "Source-monitoring error", back: "A memory derived from one source is misattributed to another source" },
    { front: "Recall", back: "A measure of retention that requires participants to reproduce information on their own without any cues" },
    { front: "Recognition", back: "A measure of retention that requires participants to select previously learned information from an array of options" },
    { front: "Relearning", back: "A measure of retention requiring a participant to memorize information a second time to determine how much time or practice is saved" },
    { front: "Decay theory", back: "Forgetting occurs because memory traces fade with time" },
    { front: "Retroactive interference", back: "New information impairs the retention of previously learned information" },
    { front: "Interference theory", back: "People forget information because of competition from other material" },
    { front: "Proactive interference", back: "Previously learned information interferes with the retention of new information" },
    { front: "Encoding specificity principle", back: "The value of a retrieval cue depends on how well it corresponds to the memory code" }
  ];